Repository projectsyn/component-argocd, pull requests merged in 2022-03, with the labels that each got.

#65 Make Vault integration more configurable
  component/repo-server.jsonnet
  tests/defaults.yml
  tests/golden/defaults/argocd/argocd/30_repo-server/configmap.yaml
  tests/golden/defaults/argocd/argocd/30_repo-server/deployment.yaml
  tests/golden/openshift/argocd/argocd/30_repo-server/configmap.yaml
  tests/golden/openshift/argocd/argocd/30_repo-server/deployment.yaml
  tests/golden/params/argocd/argocd/30_repo-server/configmap.yaml
  tests/golden/params/argocd/argocd/30_repo-server/deployment.yaml
Labels: enhancement

#66 Add custom health check for OLM subscriptions
  component/config.jsonnet
  tests/golden/defaults/argocd/argocd/10_config/10_argocd-cm.yaml
  tests/golden/openshift/argocd/argocd/10_config/10_argocd-cm.yaml
  tests/golden/params/argocd/argocd/10_config/10_argocd-cm.yaml
Labels: enhancement

#67 Fix file permissions for vault agent sink
  component/repo-server.jsonnet
  tests/golden/defaults/argocd/argocd/30_repo-server/configmap.yaml
  tests/golden/openshift/argocd/argocd/30_repo-server/configmap.yaml
  tests/golden/params/argocd/argocd/30_repo-server/configmap.yaml
Labels: bug

#68 Configure Renovate `postUpgradeTasks`
  renovate.json
Labels: enhancement

#70 Fix `mount_path` key location
  component/repo-server.jsonnet
  tests/golden/defaults/argocd/argocd/30_repo-server/configmap.yaml
Labels: bug

#73 Update modulesync config
  .sync.yml
Labels: ignore

#75 Ensure monitoring is enabled on OCP4 clusters
  component/config.jsonnet
  tests/golden/defaults/argocd/argocd/10_config/00_namespace.yaml
  tests/golden/openshift/argocd/argocd/10_config/00_namespace.yaml
  tests/golden/params/argocd/argocd/10_config/00_namespace.yaml
Labels: bug

#56 Update dependency docker.io/library/redis to v6.2.6
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/40_redis/deployment.yaml
  tests/golden/openshift/argocd/argocd/40_redis/deployment.yaml
  tests/golden/params/argocd/argocd/40_redis/deployment.yaml
Labels: dependency

#62 Update docker.io/projectsyn/kapitan commit hash to 1cc6b83
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_repo-server/deployment.yaml
  tests/golden/openshift/argocd/argocd/30_repo-server/deployment.yaml
  tests/golden/params/argocd/argocd/30_repo-server/deployment.yaml
Labels: dependency
