Repository projectsyn/component-argocd, pull requests merged in 2022-01, with the labels that each got.

#50 Correctly specify test make target in modulesync config
  .sync.yml
Labels: ignore

#52 Fix image overrides
  component/redis.jsonnet
  component/repo-server.jsonnet
  tests/defaults.yml
  tests/golden/defaults/argocd/argocd/20_application-controller/statefulset.yaml
  tests/golden/defaults/argocd/argocd/30_repo-server/deployment.yaml
  tests/golden/defaults/argocd/argocd/40_redis/deployment.yaml
  tests/golden/defaults/argocd/argocd/50_server/deployment.yaml
  tests/golden/openshift/argocd/argocd/30_repo-server/deployment.yaml
  tests/golden/openshift/argocd/argocd/40_redis/deployment.yaml
Labels: bug

#53 Make distribution configurable instead of directly reading facts
  class/defaults.yml
  component/redis.jsonnet
  component/repo-server.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: change
