Repository projectsyn/component-argocd, pull requests merged in 2023-01, with the labels that each got.

#103 Upgrade ArgoCD to v2.3.12
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/20_application-controller/statefulset.yaml
  tests/golden/defaults/argocd/argocd/30_repo-server/deployment.yaml
  tests/golden/defaults/argocd/argocd/50_server/deployment.yaml
  tests/golden/openshift/argocd/argocd/20_application-controller/statefulset.yaml
  tests/golden/openshift/argocd/argocd/30_repo-server/deployment.yaml
  tests/golden/openshift/argocd/argocd/50_server/deployment.yaml
  tests/golden/params/argocd/argocd/20_application-controller/statefulset.yaml
  tests/golden/params/argocd/argocd/30_repo-server/deployment.yaml
  tests/golden/params/argocd/argocd/50_server/deployment.yaml
Labels: dependency

#104 Update `git.vshn.net` keys after Gitlab migration
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/10_config/10_argocd-ssh-known-hosts-cm.yaml
  tests/golden/openshift/argocd/argocd/10_config/10_argocd-ssh-known-hosts-cm.yaml
  tests/golden/params/argocd/argocd/10_config/10_argocd-ssh-known-hosts-cm.yaml
Labels: change

#106 Add aggregated cluster roles for ArgoCD custom resources
  component/rbac.jsonnet
  tests/golden/defaults/argocd/argocd/01_rbac/syn-argocd-edit-clusterrole.yaml
  tests/golden/defaults/argocd/argocd/01_rbac/syn-argocd-view-clusterrole.yaml
  tests/golden/openshift/argocd/argocd/01_rbac/syn-argocd-edit-clusterrole.yaml
  tests/golden/openshift/argocd/argocd/01_rbac/syn-argocd-view-clusterrole.yaml
  tests/golden/params/argocd/argocd/01_rbac/syn-argocd-edit-clusterrole.yaml
  tests/golden/params/argocd/argocd/01_rbac/syn-argocd-view-clusterrole.yaml
Labels: enhancement
