Repository projectsyn/component-argocd, pull requests merged in 2023-11, with the labels that each got.

#90 Update quay.io/argoproj/argocd Docker tag to v2.9.1
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency

#118 Update docker.io/bitnami/kubectl Docker tag to v1.28.4
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/openshift/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/params/argocd/argocd/25_hooks/hooks.yaml
Labels: dependency

#119 Update docker.io/library/vault Docker tag to v1.13.3
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency

#129 Rename ServiceMonitors so they don't get deleted by operator
  component/monitoring.libsonnet
  tests/golden/defaults/argocd/argocd/01_namespace/20_monitoring.yaml
  tests/golden/openshift/argocd/argocd/01_namespace/20_monitoring.yaml
  tests/golden/params/argocd/argocd/01_namespace/20_monitoring.yaml
Labels: bug

#128 Implement Kapitan plugin as ConfigMamangementPlugin sidecar
  class/defaults.yml
  component/argocd.jsonnet
  component/common.libsonnet
  tests/golden/defaults/argocd/argocd/30_argocd/00_kapitan_plugin_config.yaml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/00_kapitan_plugin_config.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/00_kapitan_plugin_config.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
Labels: change

#82 Update docker.io/library/redis Docker tag to v7
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency

#122 Update gcr.io/kubebuilder/kube-rbac-proxy Docker tag to v0.15.0
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
Labels: dependency

#131 Update argocd-operator to v0.7.0
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
Labels: dependency

#134 Update quay.io/argoproj/argocd Docker tag to v2.9.2
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency

#133 Remove support for legacy `image` field for image specifications
  component/common.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/params/argocd/argocd/25_hooks/hooks.yaml
Labels: breaking

#137 Fix label selectors for ArgoCD servicemonitors
  component/monitoring.libsonnet
  tests/golden/defaults/argocd/argocd/01_namespace/20_monitoring.yaml
  tests/golden/openshift/argocd/argocd/01_namespace/20_monitoring.yaml
  tests/golden/params/argocd/argocd/01_namespace/20_monitoring.yaml
Labels: bug
