Repository projectsyn/component-argocd, pull requests merged in 2024-12, with the labels that each got.

#212 chore(deps): update docker.io/bitnami/kubectl:1.30.7 docker digest to 1249fc2
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/openshift/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/params/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/prometheus/argocd/argocd/25_hooks/hooks.yaml
Labels: dependency, automerge, bump:patch

#213 chore(deps): update quay.io/argoproj/argocd docker tag to v2.13.2
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/prometheus/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency, automerge, bump:patch

#214 Sort parameters documentation to match `class/defaults.yml`
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: documentation

#215 Add support for https catalog repo
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  component/argocd.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/https-catalog/argocd/apps/00_default-project.yaml
  tests/golden/https-catalog/argocd/apps/00_syn-project.yaml
  tests/golden/https-catalog/argocd/apps/01_rootapp.yaml
  tests/golden/https-catalog/argocd/apps/10_argocd.yaml
  tests/golden/https-catalog/argocd/argocd/01_namespace/00_namespace.yaml
  tests/golden/https-catalog/argocd/argocd/01_namespace/20_monitoring.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_appprojects.argoproj.io.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocdexports.argoproj.io.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocds.argoproj.io.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_notificationsconfigurations.argoproj.io.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrole_syn-argocd-operator-manager-role.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrole_syn-argocd-operator-metrics-reader.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrole_syn-argocd-operator-proxy-role.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrolebinding_syn-argocd-operator-manager-rolebinding.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrolebinding_syn-argocd-operator-proxy-rolebinding.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_role_syn-argocd-operator-leader-election-role.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_rolebinding_syn-argocd-operator-leader-election-rolebinding.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/v1_configmap_syn-argocd-operator-manager-config.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/v1_namespace_syn-argocd-operator.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/v1_service_syn-argocd-operator-controller-manager-metrics-service.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/v1_service_syn-argocd-operator-webhook-service.yaml
  tests/golden/https-catalog/argocd/argocd/10_operator/v1_serviceaccount_syn-argocd-operator-controller-manager.yaml
  tests/golden/https-catalog/argocd/argocd/20_rbac/syn-argocd-edit-clusterrole.yaml
  tests/golden/https-catalog/argocd/argocd/20_rbac/syn-argocd-view-clusterrole.yaml
  tests/golden/https-catalog/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/https-catalog/argocd/argocd/30_argocd/00_kapitan_plugin_config.yaml
  tests/golden/https-catalog/argocd/argocd/30_argocd/00_ssh_secret.yaml
  tests/golden/https-catalog/argocd/argocd/30_argocd/00_vault_agent_config.yaml
  tests/golden/https-catalog/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/https-catalog/argocd/argocd/30_argocd/10_refresh_argocd_tls.yaml
  tests/golden/https-catalog/argocd/argocd/30_argocd/20_networkpolicy.yaml
  tests/golden/https-catalog/argocd/argocd/90_instances/00_argocds.yaml
  tests/golden/https-catalog/argocd/argocd/90_instances/10_approjects.yaml
  tests/https-catalog.yml
Labels: enhancement, bump:minor

#218 Disable pruning for automated sync of root app
  component/app.jsonnet
  tests/golden/defaults/argocd/apps/01_rootapp.yaml
  tests/golden/https-catalog/argocd/apps/01_rootapp.yaml
  tests/golden/openshift/argocd/apps/01_rootapp.yaml
  tests/golden/params/argocd/apps/01_rootapp.yaml
  tests/golden/prometheus/argocd/apps/01_rootapp.yaml
Labels: enhancement, bump:minor
