Repository projectsyn/component-argocd, pull requests merged in 2024-11, with the labels that each got.

#199 chore(deps): update docker.io/kapicorp/kapitan docker tag to v0.34.1
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/prometheus/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency, bump:minor

#201 chore(deps): update quay.io/argoproj/argocd docker tag to v2.11.12
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/prometheus/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency, automerge, bump:patch

#202 chore(deps): update docker.io/bitnami/kubectl:1.30.6 docker digest to 74ce0f8
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/openshift/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/params/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/prometheus/argocd/argocd/25_hooks/hooks.yaml
Labels: dependency, automerge, bump:patch

#203 Support overriding configuration for syn-argocd
  class/defaults.yml
  component/argocd.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/openshift.yml
Labels: enhancement

#179 chore(deps): update docker.io/library/redis docker tag to v7.4.1
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/prometheus/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency

#174 chore(deps): update quay.io/argoprojlabs/argocd-operator docker tag to v0.12.2
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_appprojects.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocdexports.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocds.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_notificationsconfigurations.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/defaults/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrole_syn-argocd-operator-manager-role.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_appprojects.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocdexports.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocds.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_notificationsconfigurations.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/openshift/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrole_syn-argocd-operator-manager-role.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_appprojects.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocdexports.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocds.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_notificationsconfigurations.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/params/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrole_syn-argocd-operator-manager-role.yaml
  tests/golden/prometheus/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/prometheus/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/prometheus/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_appprojects.argoproj.io.yaml
  tests/golden/prometheus/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocdexports.argoproj.io.yaml
  tests/golden/prometheus/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocds.argoproj.io.yaml
  tests/golden/prometheus/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_notificationsconfigurations.argoproj.io.yaml
  tests/golden/prometheus/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/prometheus/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrole_syn-argocd-operator-manager-role.yaml
Labels: dependency

#181 chore(deps): update quay.io/argoproj/argocd docker tag to v2.13.0
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/prometheus/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency, bump:minor

#206 chore(deps): update docker.io/bitnami/kubectl:1.30.6 docker digest to 7cada9a
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/openshift/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/params/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/prometheus/argocd/argocd/25_hooks/hooks.yaml
Labels: dependency, automerge, bump:patch

#207 chore(deps): update docker.io/bitnami/kubectl:1.30.6 docker digest to 41eecd0
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/openshift/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/params/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/prometheus/argocd/argocd/25_hooks/hooks.yaml
Labels: dependency, automerge, bump:patch

#208 chore(deps): update quay.io/argoproj/argocd docker tag to v2.13.1
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/prometheus/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency, automerge, bump:patch

#209 chore(deps): update docker.io/bitnami/kubectl docker tag to v1.30.7
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/openshift/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/params/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/prometheus/argocd/argocd/25_hooks/hooks.yaml
Labels: dependency, automerge, bump:patch

#210 Fix comparsion error when using server-side apply
  component/app.jsonnet
  tests/golden/defaults/argocd/apps/10_argocd.yaml
  tests/golden/openshift/argocd/apps/10_argocd.yaml
  tests/golden/params/argocd/apps/10_argocd.yaml
  tests/golden/prometheus/argocd/apps/10_argocd.yaml
Labels: bug, bump:patch
