Repository projectsyn/component-argocd, pull requests merged in 2024-02, with the labels that each got.

#120 Update quay.io/argoprojlabs/argocd-operator Docker tag to v0.8.0
  class/argocd.yml
  class/defaults.yml
  component/app.jsonnet
  component/argocd.jsonnet
  component/operator.jsonnet
  docs/modules/ROOT/pages/how-tos/upgrade-v7-v8.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/partials/nav.adoc
  postprocess/fix_manifests.jsonnet
  tests/defaults.yml
  tests/golden/defaults/argocd/apps/10_argocd.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocdexports.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocds.argoproj.io.yaml
  tests/golden/defaults/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/defaults/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrole_syn-argocd-operator-manager-role.yaml
  tests/golden/defaults/argocd/argocd/10_operator/v1_service_syn-argocd-operator-controller-manager-metrics-service.yaml
  tests/golden/defaults/argocd/argocd/10_operator/v1_service_syn-argocd-operator-webhook-service.yaml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/apps/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocdexports.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocds.argoproj.io.yaml
  tests/golden/openshift/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/openshift/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrole_syn-argocd-operator-manager-role.yaml
  tests/golden/openshift/argocd/argocd/10_operator/v1_service_syn-argocd-operator-controller-manager-metrics-service.yaml
  tests/golden/openshift/argocd/argocd/10_operator/v1_service_syn-argocd-operator-webhook-service.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/apps/10_argocd.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applications.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_applicationsets.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocdexports.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apiextensions.k8s.io_v1_customresourcedefinition_argocds.argoproj.io.yaml
  tests/golden/params/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/params/argocd/argocd/10_operator/rbac.authorization.k8s.io_v1_clusterrole_syn-argocd-operator-manager-role.yaml
  tests/golden/params/argocd/argocd/10_operator/v1_service_syn-argocd-operator-controller-manager-metrics-service.yaml
  tests/golden/params/argocd/argocd/10_operator/v1_service_syn-argocd-operator-webhook-service.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
  tests/openshift.yml
  tests/params.yml
Labels: breaking

#145 Update docker.io/library/redis Docker tag to v7.2.4
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency

#142 Update docker.io/bitnami/kubectl Docker tag to v1.28.7
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/openshift/argocd/argocd/25_hooks/hooks.yaml
  tests/golden/params/argocd/argocd/25_hooks/hooks.yaml
Labels: dependency

#139 Update quay.io/argoproj/argocd Docker tag to v2.9.6
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency

#141 Update docker.io/hashicorp/vault Docker tag to v1.15.5
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency

#151 Allow creation of ArgoCDs and AppProjects
  class/argocd.yml
  class/defaults.yml
  component/instances.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/argocd/argocd/90_instances/00_argocds.yaml
  tests/golden/defaults/argocd/argocd/90_instances/10_approjects.yaml
  tests/golden/openshift/argocd/argocd/90_instances/00_argocds.yaml
  tests/golden/openshift/argocd/argocd/90_instances/10_approjects.yaml
  tests/golden/params/argocd/argocd/90_instances/00_argocds.yaml
  tests/golden/params/argocd/argocd/90_instances/10_approjects.yaml
  tests/params.yml
Labels: enhancement

#152 Default values for AppProjects
  component/instances.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/params/argocd/argocd/90_instances/10_approjects.yaml
  tests/params.yml
Labels: enhancement
