Repository projectsyn/component-argocd, pull requests merged in 2025-04, with the labels that each got.

#230 Support configuring arbitrary argocd-operator environment variables
  class/defaults.yml
  component/operator.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/params/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/params.yml
Labels: enhancement

#231 Implement support for deploying custom ArgoCD cluster roles
  class/defaults.yml
  component/common.libsonnet
  component/operator.jsonnet
  component/rbac.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/params/argocd/argocd/10_operator/apps_v1_deployment_syn-argocd-operator-controller-manager.yaml
  tests/golden/params/argocd/argocd/20_rbac/custom_controller_clusterrole.yaml
  tests/golden/params/argocd/argocd/20_rbac/custom_server_clusterroles.yaml
  tests/params.yml
Labels: enhancement, bump:minor

#233 chore(deps): update quay.io/argoproj/argocd docker tag to v2.13.7
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/https-catalog/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/prometheus/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/syn-teams/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency, automerge, bump:patch

#234 chore(deps): update docker.io/library/redis docker tag to v7.4.3
  class/defaults.yml
  tests/golden/defaults/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/https-catalog/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/openshift/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/params/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/prometheus/argocd/argocd/30_argocd/10_argocd.yaml
  tests/golden/syn-teams/argocd/argocd/30_argocd/10_argocd.yaml
Labels: dependency, automerge, bump:patch
